### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by angelmvillegas** [number0x37/TeslaDecrypt#1]
BOOLEAN bRetVal = false;

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L61

This is right

**Comment by angelmvillegas** [comment]
Should this be "false" to be consistent

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L124

**Comment by angelmvillegas** [comment]
Should this be bRetVal = true; for consistency

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L126

**Comment by angelmvillegas** [comment]
if (pbMasterKeyStripped) *pbMasterKeyStripped = false;

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L134

**Comment by angelmvillegas** [comment]
BOOLEAN bRetVal = false;

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L171

**Comment by angelmvillegas** [comment]
BOOLEAN bRetVal = false;

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L268

**Comment by angelmvillegas** [comment]
```
BOOLEAN bRetVal = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L473

**Comment by angelmvillegas** [comment]
```
BOOLEAN bRetVal = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L112

```
if (impKey) {delete impKey; bRetVal = TRUE; }
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L210

```
BOOLEAN bRetVal = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L267

```
BOOL bProcRetVal = false,
		bRetVal = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L388

```
bRetVal = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L437

```
BOOLEAN bRetVal = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L497

```
BOOL bRetVal = false;						// Returned value
BOOL bMasterKeyStripped = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L567

```
HANDLE hNewScreenBuffer = false;
BOOL retVal = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L655

```
BOOL bConsoleOk = false;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L674

```
return (bConsoleOk != FALSE);
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L681

**Comment by AaLl86** [comment]
Fixed, need some talk
