### ISSUE TITLE
Add else statement to prevent bugs

### ISSUE THREAD

**Issue by angelmvillegas** [number0x37/TeslaDecrypt#2]
should there be an else statement? If by some chance the file's size is less than 0x177 then line 111 will cause the masterKey buffer to be outside the file's contents. If the file is less than 0x126 bytes then line 103 will read beyond the buffer.

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L92

**Comment by AaLl86** [comment]
Fixed... Good advice!
