### ISSUE TITLE
Delete/Reduce/Optimize Code

### ISSUE THREAD

**Issue by angelmvillegas** [number0x37/TeslaDecrypt#5]
The boolean statement complicates this and can be reduced to 

return bRetVal;

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L142

No it can't. "bool" type is different from BOOLEAN

**Comment by angelmvillegas** [comment]
Another instance:

return bRetVal;

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L163

**Comment by angelmvillegas** [comment]
couldn't lines 374-378 become:
```
return !bSomeErrors;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L374

\- - or - - 

couldn't lines 373-378 become:
```
return bAtLeastOneDecrypted || !bSomeErrors;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L373

**Comment by angelmvillegas** [comment]
Same as above comment but with bAtLeastOneDriveOk

```
return bAtLeastOneDriveOk || !bSomeErrors;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L423

**Comment by angelmvillegas** [comment]
```
return bRetVal;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L484

**Comment by angelmvillegas** [comment]
Line not needed, delete

https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypter.cpp#L516

**Comment by angelmvillegas** [comment]
Couldn't this be simplified from:
```
return (bRetVal != 0 ? 1 : -1);
```
to the below statement to make it easier to understand?
```
return (bRetVal ? 1 : -1);
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L344

Line not used, delete
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L656

```
return bConsoleOk;
```
https://github.com/number0x37/TeslaDecrypt/blob/master/Cpp/TeslaDecrypterApp.cpp#L681

**Comment by AaLl86** [comment]
Fixed
