### ISSUE TITLE
Move Python imports outside of main function

### ISSUE THREAD

**Issue by angelmvillegas** [number0x37/TeslaDecrypt#9]
move lines 48-56 to line 42, or outside of the main function
move line 161 outside of main function

https://github.com/number0x37/TeslaDecrypt/blob/master/Python/TeslaDecrypt.py#L48
https://github.com/number0x37/TeslaDecrypt/blob/master/Python/TeslaDecrypt.py#L161

**Comment by shahurle** [comment]
fixed
